# Generated by Django 6.0.3 on 2026-04-07 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0006_alter_product_stock_minimo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(max_length=150)),
                ('numero_documento', models.CharField(max_length=50)),
                ('fecha_documento', models.DateField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='recepciones/')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_RECEPCION', 'En recepción'), ('PENDIENTE_APROBACION', 'Pendiente aprobación'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='BORRADOR', max_length=30)),
                ('observacion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recepciones_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones_creadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=40)),
                ('codigo_barra', models.CharField(blank=True, max_length=50)),
                ('nombre', models.CharField(blank=True, max_length=150)),
                ('cantidad_esperada', models.PositiveIntegerField()),
                ('cantidad_recibida', models.PositiveIntegerField(default=0)),
                ('incidencia_faltante', models.PositiveIntegerField(default=0)),
                ('incidencia_merma', models.PositiveIntegerField(default=0)),
                ('incidencia_sobrante', models.PositiveIntegerField(default=0)),
                ('observacion', models.TextField(blank=True)),
                ('recepcionado', models.BooleanField(default=False)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
                ('recepcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='receiving.receipt')),
            ],
        ),
    ]
