# Generated by Django 6.0.3 on 2026-03-15 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_codigo_barra'),
        ('receiving', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptdetail',
            name='codigo_barra',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='receiptdetail',
            name='nombre',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='receiptdetail',
            name='sku',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='receiptdetail',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.product'),
        ),
    ]
