# Generated by Django 6.0.3 on 2026-03-15 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiving', '0002_receiptdetail_codigo_barra_receiptdetail_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptdetail',
            name='incidencia_faltante',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='receiptdetail',
            name='incidencia_merma',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='receiptdetail',
            name='incidencia_sobrante',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='receiptdetail',
            name='recepcionado',
            field=models.BooleanField(default=False),
        ),
    ]
