# Generated by Django 6.0.3 on 2026-03-04 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.location')),
            ],
            options={
                'unique_together': {('producto', 'ubicacion')},
            },
        ),
    ]
