# Generated by Django 6.0.3 on 2026-04-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='codigo_contenedor',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='codigo_ubicacion',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
