# Generated by Django 6.0.3 on 2026-03-12 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlocation',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
