# Generated by Django 6.0.3 on 2026-04-07 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_alter_container_codigo_contenedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='codigo_barra_imagen',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='location',
            name='codigo_barra_imagen',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
    ]
