# Generated by Django 6.0.3 on 2026-04-14 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_product_categoria'),
        ('warehouse', '0003_container_codigo_barra_imagen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('contenedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_containers', to='warehouse.container')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_containers', to='catalog.product')),
            ],
        ),
    ]
