# Generated by Django 6.0.3 on 2026-04-12 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('warehouse', '0003_container_codigo_barra_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='contenedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.container'),
        ),
    ]
