# Generated by Django 6.0.3 on 2026-04-12 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_product_categoria'),
        ('inventory', '0002_movement_contenedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='catalog.product'),
        ),
    ]
