# Generated by Django 6.0.3 on 2026-03-12 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_movement_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('MERMA', 'Merma'), ('UBICACION', 'Ubicación')], max_length=15),
        ),
    ]
