# Generated by Django 6.0.3 on 2026-04-14 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_product_categoria'),
        ('inventory', '0004_productcontainer'),
        ('warehouse', '0003_container_codigo_barra_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcontainer',
            name='contenedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_product_containers', to='warehouse.container'),
        ),
        migrations.AlterField(
            model_name='productcontainer',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_product_containers', to='catalog.product'),
        ),
    ]
