# Generated by Django 6.0.3 on 2026-04-17 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_productcontainer_contenedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('MERMA', 'Merma'), ('UBICACION', 'Ubicación'), ('TRANSFERENCIA', 'Transferencia')], max_length=15),
        ),
    ]
