# Generated by Django 6.0.3 on 2026-03-11 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='codigo_barra',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='codigo_interno',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
