# Generated by Django 6.0.3 on 2026-03-11 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_codigo_barra_product_codigo_interno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='codigo_interno',
            field=models.CharField(blank=True, max_length=13, unique=True),
        ),
    ]
