# Generated by Django 6.0.3 on 2026-03-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_codigo_interno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='codigo_barra',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
