# Generated by Django 6.0.3 on 2026-03-21 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_codigo_barra'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='estado',
            field=models.CharField(choices=[('OK', 'OK'), ('ALERTA', 'ALERTA')], default='OK', max_length=20),
        ),
    ]
