# Generated by Django 6.0.3 on 2026-03-31 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
