# Generated by Django 6.0.3 on 2026-03-20 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickingorder',
            name='factura',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pickingorder',
            name='numero_orden',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
