# Generated by Django 6.0.3 on 2026-04-15 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picking', '0001_initial'),
        ('warehouse', '0004_productcontainer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickingdetail',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='pickingdetail',
            name='contenedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.container'),
        ),
    ]
