# Generated by Django 6.0.3 on 2026-03-20 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picking', '0002_pickingorder_factura_pickingorder_numero_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickingorder',
            name='factura',
            field=models.CharField(blank=True, default='SIN_GUIA', max_length=20),
        ),
        migrations.AlterField(
            model_name='pickingorder',
            name='numero_orden',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
