# Generated by Django 6.0.3 on 2026-03-20 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picking', '0003_alter_pickingorder_factura_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='pickingdetail',
            name='confirmado',
        ),
        migrations.RemoveField(
            model_name='pickingdetail',
            name='confirmado_en',
        ),
        migrations.AddField(
            model_name='pickingdetail',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('COMPLETADO', 'Completado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='pickingdetail',
            name='prioridad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pickingdetail',
            name='operario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pickingdetail',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='picking.producto'),
        ),
        migrations.AlterField(
            model_name='pickingdetail',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='picking.ubicacion'),
        ),
    ]
