# Generated by Django 6.0.3 on 2026-03-20 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_codigo_barra'),
        ('picking', '0004_producto_ubicacion_remove_pickingdetail_confirmado_and_more'),
        ('warehouse', '0002_productlocation_cantidad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickingdetail',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='pickingdetail',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.location'),
        ),
        migrations.RemoveField(
            model_name='pickingdetail',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='pickingdetail',
            name='prioridad',
        ),
        migrations.AddField(
            model_name='pickingdetail',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pickingdetail',
            name='confirmado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pickingdetail',
            name='operario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickings_operario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Ubicacion',
        ),
    ]
