# Generated by Django 6.0.3 on 2026-03-20 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picking', '0005_alter_pickingdetail_producto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickingdetail',
            name='confirmado',
        ),
        migrations.RemoveField(
            model_name='pickingdetail',
            name='confirmado_en',
        ),
        migrations.AddField(
            model_name='pickingdetail',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('COMPLETADO', 'Completado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='pickingdetail',
            name='prioridad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pickingdetail',
            name='operario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
